# These are supported funding model platforms

github: zfbx
patreon: zfbx
ko_fi: zfbx8
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.buymeacoffee.com/zfbx', 'https://paypal.me/zfbx']
