title: zdiscord
author:
  name: zfbx
description: > # this means to ignore newlines until "show_excerpts:"
  A Discord bot that runs in FiveM for the purpose of whitelisting, moderation
  and utilties. Easy to use, setup and expand upon while giving great tools and QBCore support
show_excerpts: false # set to true to show excerpts on the homepage


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: sighingnow/jekyll-gitbook
